# Project information
site_name: Android Burstcoin Wallet
site_description: Documentation for the Android Burstcoin Wallet
site_author: cgb
site_url: https://github.com/poc-consortium/burstcoin-mobile-doc
site_favicon: img/favicon.ico

# Repository
repo_name: poc-consortium/burstcoin-mobile
repo_url: https://github.com/poc-consortium/burstcoin-mobile-doc

# Options
extra:
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  social:
    - type: github-alt
      link: https://github.com/poc-consortium
    - type: twitter
      link: https://twitter.com/PoC_Consortium

# Page tree
pages:
  - Documentation: index.md
  - Wallet:
      - Create Account: wallet/create.md
      - Import Account: wallet/import.md
      - Activate Account: wallet/activate.md
      - Switch Account: wallet/switch.md
      - Remove Account: wallet/remove.md
  - PIN Code: pin.md
  - Send Burstcoins: send.md
  - Transaction History: transactions.md
  - Privacy Policy: privacy_policy.md

theme: 'material'

# Google Analytics
google_analytics:
  - UA-104373595-4
  - auto
